services:
  - type: web
    name: SADEW-XMD-V2
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PREFIX
        value: "."
      - key: MODE
        value: "public"
      - key: OWNER_NUMBER
        sync: false
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "8000"
      - key: ALIVE_IMG
        value: "https://files.catbox.moe/f18ceb.jpg"
      - key: MENU_IMG
        value: "https://files.catbox.moe/f18ceb.jpg"
      - key: PACKNAME
        value: "SADEW-XMD V2"
      - key: AUTHOR
        value: "SADEW TECH"
      - key: ALWAYS_ONLINE
        value: "true"
      - key: AUTO_VOICE
        value: "false"
      - key: AUTO_AI
        value: "false"
      - key: ANTI_BAD_WORDS_ENABLED
        value: "false"
      - key: ANTI_DELETE
        value: "false"
      - key: ANTILINK
        value: "false"
